### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by ryanlmelvin** [melih-unsal/DemoGPT#1]
**Describe the bug**

**To Reproduce**
Run the streamlit app with an idea submitted.

**Expected behavior**
A demo app is produced

**Desktop (please complete the following information):**
 - Windows 11
 - Streamlit
 - Edge

**Additional context**
It appears there are some hardcoded paths unique to the original development environment. For example:
FileNotFoundError: [Errno 2] No such file or directory: '/home/melih/anaconda3/envs/synthdata/bin/streamlit'

**Comment by melih-unsal** [comment]
Hey @ryanlmelvin , 

Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to hardcoded paths specific to the original development environment, as you rightly pointed out.

I'm glad to inform you that we've pushed a new update to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.

Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.

Thank you for your support and contribution to DemoGPT.

Best,
Melih

**Comment by melih-unsal** [comment]
We believe this update should resolve the issue, so I'll go ahead and close this issue for now. However, if you find that the problem persists, please feel free to reopen it or create a new issue.
