### ISSUE TITLE
Dependencies need upgrading

### ISSUE THREAD

**Issue by MichaelJThomas-2016** [melih-unsal/DemoGPT#26]
**Describe the bug**
When cloning and running `streamlit run src/prompt_based/app.py` Streamlit complains about `ModuleNotFoundError: No module named 'altair.vegalite.v4'

**To Reproduce**
1. Clone
2. Install requirements.txt
3. run `streamlit run src/prompt_based/app.py`

**Expected behavior**
N/A

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Issue seems to be to add `altair>=4.0`
https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/2

**Comment by melih-unsal** [comment]
Hey @MichaelJThomas-2016  ,

Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to the `altair` library version issue as you rightly pointed out.

I'm glad to inform you that we've made a new PR to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.

Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.

Thank you for your support and contribution to DemoGPT.

Best,
Melih

**Comment by melih-unsal** [comment]
If the issue still exists, you can reopen it and type the issue.

**Comment by MichaelJThomas-2016** [comment]
Sounds good.

I tinkered with it on my laptop, but seems like there’s an issue with the
stream lit code.

You call st.progress which only takes 1 int. Argument. Not sure if that’s
because I have a different version of streamlit, but might be worth
checking out.

**Comment by melih-unsal** [comment]
Hi @MichaelJThomas-2016 ,

Thanks for your great feedback :pray: 

I checked the code but was not able to see any case where st.progress takes only 1 parameter. Is it the case in the generated code or the repo itself? I would really appreciate it if you point out the case.
