### ISSUE TITLE
[Windows] Missing dotenv module

### ISSUE THREAD

**Issue by jcalebsmith** [melih-unsal/DemoGPT#3]
**Describe the bug**
Following a fresh installation in new virtual environment with Python 3.10.11, I'm getting ModuleNotFoundError for termcolor. After installing termcolor with pip, I then get ModuleNotFoundError for dotenv. Unfortunately, I've been unable to install dotenv with pip or with 'pip install dotenv' or 'pip install --use-pep517 dotenv'

**To Reproduce**
1. Create a new virtual env with python 3.10
2. git clone https://github.com/melih-unsal/DemoGPT.git
3. cd DemoGPT
4. pip install -r requirements.txt
5. cd src/prompt_based
6. streamlit run app.py

**Expected behavior**
Streamlit inititates successfully

**Screenshots**
![image](https://github.com/melih-unsal/DemoGPT/assets/48289425/b7a1f2ce-0130-453a-b077-ba8ca112b7a8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**

**Comment by jcalebsmith** [comment]
Ah! Running 'pip install python-dotenv' from terminal resolves the issue.

**Comment by melih-unsal** [comment]
Hey @jcalebsmith ,

Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to the lack of python-dotenv library in requirements.txt, as you rightly pointed out.

I'm glad to inform you that we've pushed a new update to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.

Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.

Thank you for your support and contribution to DemoGPT.

Best,
Melih
