### ISSUE TITLE
Delete the incorrect contact information in the project

### ISSUE THREAD

**Issue by wusiyaodiudiu** [melih-unsal/DemoGPT#38]
**Describe the bug**
There is a wechat QR code in the folder “docs/resources/”.
I added him on wechat. He's a developer of the project “MetaGPT”.
Whether forget to delete this file when copying the code from MetaGPT.
It is recommended to delete this file and note if the MetaGPT project is referenced

**Comment by melih-unsal** [comment]
Hello @wusiyaodiudiu ,

I appreciate you bringing this to our attention. To be honest, we weren't aware that the QR code was associated with the MetaGPT developer. WeChat isn't prevalent in our country, so there was some confusion on our end. My apologies for that oversight.

If you take a closer look at our codebase, you'll see that there's no code lifted from MetaGPT. It's entirely our own work. The inclusion of the WeChat link was an unintended error. The reason for the Chinese explanations in our repo was purely out of respect. We recognize the immense talent among Chinese developers and aimed to connect with them.

We've since removed the file in question.

Best regards,

Melih.

**Comment by wusiyaodiudiu** [comment]
@melih-unsal I appreciate your prompt response.   
I find both MetaGPT and DemoGPT to be intriguing implementation approaches.Hence, I've been keeping a close eye on both projects.   
I have indeed not come across any code similar to MetaGPT's.  It's my misspoke. 
Would it be possible for you to provide alternative contact information for further communication, or could you share how I might become a part of this project?

Best regards,
Siyao

**Comment by melih-unsal** [comment]
Hello @wusiyaodiudiu,

Firstly, thank you again for showing interest in DemoGPT! We truly appreciate your enthusiasm.

To get started with contributing, please refer to our [CONTRIBUTING.md](https://github.com/melih-unsal/DemoGPT/blob/main/CONTRIBUTING.md) guide. This document outlines the necessary steps and best practices.

At the moment, I'm focusing on improving [final.py](https://github.com/melih-unsal/DemoGPT/blob/main/demogpt/plan/chains/prompts/final.py) which is discussed in more detail [here](https://github.com/melih-unsal/DemoGPT/blob/main/CONTRIBUTING.md#modifying-the-main-prompts). Its primary function is to put finishing touches on the draft code. If you're looking for a good starting point, diving into this would be ideal. To verify your changes, you can execute the test using the following command:

`python -m unittest demogpt.plan.test.TestDemoGPT.test_final`

To test the application overall, you can run this command

`python -m unittest demogpt.plan.test.TestDemoGPT.test`

Additionally, we're about to set up a Discord Server for more real-time interactions. Stay tuned for that!

Once again, thank you for your interest, and we look forward to your contributions!
