### ISSUE TITLE
Running the App produces the error 'which python' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by haris525** [melih-unsal/DemoGPT#4]
**Describe the bug**
Running the App produces the error 'which python' returned non-zero exit status 1. Using windows 10, all dependencies are installed

**To Reproduce**
1. Launch the streamlit app
2. Under Examples click 'Language Translator

**Expected behavior**
The app should generate a streamlit application as shown in the demo

**Issue**
Running the App produces the error 'which python' returned non-zero exit status 1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
**Do I need to create a new environment, also please add other required packages in the requiremets.txt file**

**Comment by melih-unsal** [comment]
Hey @haris525 ,

Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to the which command run in Windows operating system, as you rightly pointed out.

I'm glad to inform you that we've pushed a new update to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.

Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.

Thank you for your support and contribution to DemoGPT.

Best,
Melih

**Comment by haris525** [comment]
> Hey @haris525 ,
> 
> Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to the which command run in Windows operating system, as you rightly pointed out.
> 
> I'm glad to inform you that we've pushed a new update to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.
> 
> Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.
> 
> Thank you for your support and contribution to DemoGPT.
> 
> Best, Melih

Much appreciated Melih! 

Thank you my friend
